import { runBlockProtocolSpecs } from "../src/lib/server/goalPlanning/blockProtocol.spec";
import { runTaskCompilerSpecs } from "../src/lib/server/goalPlanning/taskCompiler.spec";
import { runGoalNotificationWorkerSpecs } from "../src/lib/server/worker/goalNotificationWorker.spec";
import { runAwaitingDisplayModelSpecs } from "../src/lib/taskInstance/awaitingDisplayModel.spec";
import { runProtocolNormalizeSpecs } from "../src/lib/server/protocol/protocolNormalize.spec";
import { runPromptDuplicationGuardSpecs } from "../src/lib/planning/specs/promptDuplicationGuardSpec";
import { runRuntimeStateChannelSpecs } from "../src/lib/runtimeStateChannel.spec";
import { runRoutesSpecs } from "../src/lib/routes.spec";
import { runMiddlewareSpecs } from "../src/middleware.spec";
import { runStateSnapshotSpecs } from "../src/lib/server/runtime/stateSnapshot.spec";
import { runStorageAdapterSpecs } from "../src/lib/server/adapters/storage.spec";
import { runRuntimeEnvironmentCommandServiceSpecs } from "../src/lib/server/services/runtimeEnvironmentCommandService.spec";
import { runTaskTriggerTimeSpecs } from "../src/lib/taskTriggerTime.spec";
import { runGoalSchedulerEngineSpecs } from "../src/lib/server/worker/goalSchedulerEngine.spec";
import { runConversationCommandServiceSpecs } from "../src/lib/server/services/conversationCommandService.spec";
import { runRuntimeEventsAggregationSpecs } from "../src/lib/api/runtime-events.spec";
import { runClaudeTransportSessionSpecs } from "../src/lib/server/claude/transport.spec";
import { runClaudeTraceStoreSpecs } from "../src/lib/server/claude/traceStore.spec";
import { runContextPackBoundarySpecs } from "../src/lib/server/workspace/contextPack.spec";
import { runJsonRepairAutoCloseSpecs } from "../src/lib/server/claude/jsonRepair.spec";
import { runTaskDraftReviewSpecs } from "../src/lib/server/goalPlanning/taskDraftReview.spec";
import { runPayloadGuardSpecs } from "../src/lib/server/agentRuntime/payloadGuard.spec";
import { runClaudeJsonInvokeSpecs } from "../src/lib/server/agentRuntime/claudeJsonInvoke.spec";
import { runAgentExecutorSpecs } from "../src/lib/server/agentRuntime/agentExecutor.spec";
import { runResumeManagerSpecs } from "../src/lib/server/agentRuntime/resumeManager.spec";
import { runAgentRunCommandServiceSpecs } from "../src/lib/server/services/agentRunCommandService.spec";
import { runLegacyGoalToTopicSpecs } from "../src/lib/migration/legacyGoalToTopic.spec";
import { runSchemaSpecs } from "../src/lib/server/db/schema.spec";
import { runGoalCommandServiceSpecs } from "../src/lib/server/services/goalCommandService.spec";
import { runGoalRuntimeServiceSpecs } from "../src/lib/server/services/goalRuntimeService.spec";
import { runTopicCommandServiceSpecs } from "../src/lib/server/services/topicCommandService.spec";
import { runTopicInitSagaSpecs } from "../src/lib/server/goalPlanning/topicInitSaga.spec";
import { runTopicInitSagaDefaultsSpecs } from "../src/lib/server/goalPlanning/runTopicInitSagaDefaults.spec";
import { runSagaDraftAdapterSpecs } from "../src/lib/server/goalPlanning/sagaDraftAdapter.spec";
import { runThreadTickOutputSchemaSpecs } from "../src/lib/server/thread/threadTickOutputSchema.spec";
import { runThreadRunnerSpecs } from "../src/lib/server/thread/threadRunner.spec";
import { runThreadLoopSchedulerSpecs } from "../src/lib/server/thread/threadLoopScheduler.spec";
import { runDispatchActionsSpecs } from "../src/lib/server/thread/dispatchActions.spec";
import { runThreadLoopWorkerSpecs } from "../src/lib/server/thread/threadLoopWorker.spec";
import { runThreadsRepositorySpecs } from "../src/lib/server/repositories/threadsRepository.spec";
import { runTaskInstancesRepositorySpecs } from "../src/lib/server/repositories/taskInstancesRepository.spec";
import { runInboxRepositorySpecs } from "../src/lib/server/repositories/inboxRepository.spec";
import { runAppendThreadMessageSpecs } from "../src/lib/server/repositories/conversationMessagesRepository.spec";
import { runDispatchTaskFromThreadSpecs } from "../src/lib/server/services/dispatchTaskFromThread.spec";
import { runThreadLoopDaemonSpecs } from "../src/lib/server/scheduler/threadLoopDaemon.spec";
import { runDevPanelDataSpecs } from "../src/lib/server/repositories/agentRuntime/sagaInstancesRepository.spec";
import { runDaemonRunnerSpecs } from "../src/lib/daemon/daemonRunner.spec";

runStateSnapshotSpecs();
runTaskTriggerTimeSpecs();
runGoalSchedulerEngineSpecs();
runBlockProtocolSpecs();
runTaskCompilerSpecs();
runGoalNotificationWorkerSpecs();
runAwaitingDisplayModelSpecs();
runProtocolNormalizeSpecs();
runPromptDuplicationGuardSpecs();
runRuntimeStateChannelSpecs();
runRoutesSpecs();
runMiddlewareSpecs();
runRuntimeEnvironmentCommandServiceSpecs();
runConversationCommandServiceSpecs();
runRuntimeEventsAggregationSpecs();
runStorageAdapterSpecs();
runJsonRepairAutoCloseSpecs();
runTaskDraftReviewSpecs();
runClaudeTransportSessionSpecs();
runClaudeTraceStoreSpecs();
runContextPackBoundarySpecs();
runPayloadGuardSpecs();
runResumeManagerSpecs();
runAgentRunCommandServiceSpecs();
runLegacyGoalToTopicSpecs();
runSchemaSpecs();
runGoalCommandServiceSpecs();
runGoalRuntimeServiceSpecs();
runTopicCommandServiceSpecs();
runSagaDraftAdapterSpecs();
runThreadTickOutputSchemaSpecs();
runThreadLoopSchedulerSpecs();
runDaemonRunnerSpecs();

(async () => {
  await runAgentExecutorSpecs();
  await runClaudeJsonInvokeSpecs();
  await runTopicInitSagaSpecs();
  await runTopicInitSagaDefaultsSpecs();
  await runThreadsRepositorySpecs();
  await runTaskInstancesRepositorySpecs();
  await runInboxRepositorySpecs();
  await runAppendThreadMessageSpecs();
  await runDispatchTaskFromThreadSpecs();
  await runThreadRunnerSpecs();
  await runDispatchActionsSpecs();
  await runThreadLoopWorkerSpecs();
  await runThreadLoopDaemonSpecs();
  await runDevPanelDataSpecs();
  console.log("planning specs passed");
})().catch((error) => {
  console.error(error);
  process.exit(1);
});
