import { runBlockProtocolSpecs } from "../src/lib/server/goalPlanning/blockProtocol.spec";
import { runTaskCompilerSpecs } from "../src/lib/server/goalPlanning/taskCompiler.spec";
import { runGoalNotificationWorkerSpecs } from "../src/lib/server/worker/goalNotificationWorker.spec";
import { runAwaitingDisplayModelSpecs } from "../src/lib/taskInstance/awaitingDisplayModel.spec";
import { runProtocolNormalizeSpecs } from "../src/lib/server/protocol/protocolNormalize.spec";
import { runPromptDuplicationGuardSpecs } from "../src/lib/planning/specs/promptDuplicationGuardSpec";
import { runRuntimeStateChannelSpecs } from "../src/lib/runtimeStateChannel.spec";
import { runStateSnapshotSpecs } from "../src/lib/server/runtime/stateSnapshot.spec";
import { runGoalDeliverableServiceSpecs } from "../src/lib/server/services/goalDeliverableService.spec";
import { runStorageAdapterSpecs } from "../src/lib/server/adapters/storage.spec";
import { runRuntimeEnvironmentCommandServiceSpecs } from "../src/lib/server/services/runtimeEnvironmentCommandService.spec";
import { runTaskTriggerTimeSpecs } from "../src/lib/taskTriggerTime.spec";
import { runGoalSchedulerEngineSpecs } from "../src/lib/server/worker/goalSchedulerEngine.spec";
import { runConversationCommandServiceSpecs } from "../src/lib/server/services/conversationCommandService.spec";

runStateSnapshotSpecs();
runTaskTriggerTimeSpecs();
runGoalSchedulerEngineSpecs();
runBlockProtocolSpecs();
runTaskCompilerSpecs();
runGoalNotificationWorkerSpecs();
runAwaitingDisplayModelSpecs();
runProtocolNormalizeSpecs();
runPromptDuplicationGuardSpecs();
runRuntimeStateChannelSpecs();
runRuntimeEnvironmentCommandServiceSpecs();
runConversationCommandServiceSpecs();
runGoalDeliverableServiceSpecs();
runStorageAdapterSpecs();
console.log("planning specs passed");
